/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DuAn1_Pro1041_View;

import DuAn1_Pro1041_Model.NhanVien_Model;
import DuAn1_Pro1041_Service.NhanVien_Service;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author QuangDu
 */
public class QLNhanVien_View extends javax.swing.JFrame {
    
    DefaultTableModel defaultTableModel = new DefaultTableModel();
    NhanVien_Service nhanVienService = new NhanVien_Service();
    private List<NhanVien_Model> lists = new ArrayList<>();
    int index = -1;
    
    /**
     * Creates new form QLNhanVien
     */
    public QLNhanVien_View() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fillTable(nhanVienService.getAll());
    }
    
    public void fillTable(List<NhanVien_Model> list) {
        
        defaultTableModel =  (DefaultTableModel) tbl_nhanVien.getModel();
        defaultTableModel.setRowCount(0);
        for (NhanVien_Model nhanVien_Model : list) {
            defaultTableModel.addRow(new Object[]{
                nhanVien_Model.getMaNV(),nhanVien_Model.getMaTK(),
                nhanVien_Model.getHoTen(),nhanVien_Model.getGioiTinh(),
                nhanVien_Model.getDiaChi(),nhanVien_Model.getSdt(),nhanVien_Model.getTrangThai()
            });
        }
    }
    void showData(int index){
        NhanVien_Model nv = nhanVienService.getAll().get(index);
        txt_maNV.setText(nv.getMaNV());
        txt_maTK.setText(nv.getMaTK());
        txt_hoTen.setText(nv.getHoTen());
        if(nv.getGioiTinh()==1){
            rd_nam.setSelected(true);
        }else{
            rd_nu.setSelected(true);
        }
        txt_diaChi.setText(nv.getDiaChi());
        txt_SDT.setText(nv.getSdt());
        if (nv.getTrangThai()==1) {
            rd_hoatDong.setSelected(true);
        } else {
            rd_khongHoatDong.setSelected(true);
        }
    }
    private NhanVien_Model readform(){
       int gioiTinh,trangThai;
       String MaNV = txt_maNV.getText();
       String MaTK = txt_maTK.getText();
       String hoTen = txt_hoTen.getText();
       if(rd_nam.isSelected()){
           gioiTinh=1;
       }else{
           gioiTinh=0;
       }
       String diaChi = txt_diaChi.getText();
       String sdt = txt_SDT.getText();
       if(rd_hoatDong.isSelected()){
           trangThai=1;
       }else{
           trangThai=0;
       } 
       return new NhanVien_Model(MaNV, MaTK, hoTen, gioiTinh, diaChi, sdt, trangThai);
    }

    boolean checktrung(){
        List<NhanVien_Model> nvM = nhanVienService.getAll();
        for (int i = 0; i < nvM.size(); i++) {
            if(txt_maNV.getText().equalsIgnoreCase(nvM.get(i).getMaNV())){
                JOptionPane.showMessageDialog(this, "trung ma");
                return false;
            }
        }
        return true;
    }
    boolean Validate(){
        String sdt = txt_SDT.getText();
        String checksdt = "0\\d{9}";
        if(txt_maNV.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "ma nhan vien trong");
            return false;
        }
          if(txt_maTK.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "ma tai khoan trong");
            return false;
        }
            if(txt_hoTen.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "ho ten trong");
            return false;
        }
              if(txt_diaChi.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "dia chi trong");
            return false;
        }
                if(txt_SDT.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "so dien thoai trong");
            return false;
        }
                if(!sdt.matches(checksdt)){
                    JOptionPane.showMessageDialog(this, "dinh dang sdt sai");
                    return  false;
                }
            return true;
    }
    private void clear(){
        this.txt_maNV.setText("");
        this.txt_maTK.setText("");
        this.txt_hoTen.setText("");
        this.txt_diaChi.setText("");
        this.txt_SDT.setText("");
        this.txt_timKiem.setText("");
        this.index = -1;
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblQLND = new javax.swing.JLabel();
        txt_timKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_maNV = new javax.swing.JTextField();
        txt_maTK = new javax.swing.JTextField();
        txt_hoTen = new javax.swing.JTextField();
        rd_nam = new javax.swing.JRadioButton();
        rd_nu = new javax.swing.JRadioButton();
        txt_diaChi = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        rd_hoatDong = new javax.swing.JRadioButton();
        rd_khongHoatDong = new javax.swing.JRadioButton();
        btn_them = new javax.swing.JButton();
        btn_moi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_nhanVien = new javax.swing.JTable();
        btn_update = new javax.swing.JButton();
        btn_timKiem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQLND.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblQLND.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLND.setText("QUẢN LÝ NHÂN VIÊN");

        jLabel1.setText("MaNV");

        jLabel2.setText("MaTK");

        jLabel3.setText("HoTen");

        jLabel4.setText("GioiTinh");

        jLabel5.setText("SDT");

        jLabel6.setText("TrangThai");

        jLabel7.setText("DiaChi");

        jLabel8.setText("Tim Kiem");

        txt_hoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hoTenActionPerformed(evt);
            }
        });

        buttonGroup1.add(rd_nam);
        rd_nam.setText("Nam");

        buttonGroup1.add(rd_nu);
        rd_nu.setText("Nu");

        buttonGroup2.add(rd_hoatDong);
        rd_hoatDong.setText("Hoat dong");

        buttonGroup2.add(rd_khongHoatDong);
        rd_khongHoatDong.setText("Khong hoat dong");

        btn_them.setText("Them");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_moi.setText("Moi");
        btn_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moiActionPerformed(evt);
            }
        });

        tbl_nhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MaNV", "MaTK", "HoTen", "GioiTinh", "DiaChi", "sdt", "TrangThai"
            }
        ));
        tbl_nhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_nhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_nhanVien);

        btn_update.setText("update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_timKiem.setText("Tim kiem");
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        jButton1.setText("Trang chủ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQLND, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_them)
                            .addGap(18, 18, 18)
                            .addComponent(btn_moi)
                            .addGap(18, 18, 18)
                            .addComponent(btn_update))
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                    .addComponent(btn_timKiem))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(107, 107, 107)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_maTK, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(107, 107, 107)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(55, 55, 55)
                                            .addComponent(rd_hoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(42, 42, 42)
                                            .addComponent(rd_khongHoatDong))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(txt_SDT))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addComponent(rd_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(rd_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblQLND, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btn_timKiem))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_maTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(rd_hoatDong)
                        .addComponent(rd_khongHoatDong)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rd_nam)
                    .addComponent(rd_nu))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_moi)
                    .addComponent(btn_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_hoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hoTenActionPerformed

    private void tbl_nhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nhanVienMouseClicked
        index = tbl_nhanVien.getSelectedRow();
        this.showData(index);
    }//GEN-LAST:event_tbl_nhanVienMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        int hoi = JOptionPane.showConfirmDialog(this, "ban chac chan muon sua");
        if(hoi == 0){
            index = tbl_nhanVien.getSelectedRow();
            String maNV = tbl_nhanVien.getValueAt(index, 0).toString();
            NhanVien_Model nvM = this.readform();
            if(nhanVienService.update(nvM, maNV)>0){
                JOptionPane.showMessageDialog(this, "sua thanh cong");
                fillTable(lists);
                this.fillTable(nhanVienService.getAll());
            }else{
                JOptionPane.showMessageDialog(this, "sua that bai");
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
        
       // if(timkiem.isEmpty()){
        //    JOptionPane.showMessageDialog(this, "nhap thong tin can tim");
//        }else{
//          
//        }
          String timkiem = txt_timKiem.getText();
            fillTable(nhanVienService.Timkiem(timkiem));
            
            
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_moiActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
             NhanVien_Model nv = this.readform();
        if (nhanVienService.addnhanvien(nv)> 0) {
            JOptionPane.showMessageDialog(this, "Them thanh cong");
            fillTable(lists);
            this.fillTable(nhanVienService.getAll());
        }else{
            JOptionPane.showMessageDialog(this, "Them that bai");
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TrangChu_View tcv = new TrangChu_View();
        tcv.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNhanVien_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_moi;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQLND;
    private javax.swing.JRadioButton rd_hoatDong;
    private javax.swing.JRadioButton rd_khongHoatDong;
    private javax.swing.JRadioButton rd_nam;
    private javax.swing.JRadioButton rd_nu;
    private javax.swing.JTable tbl_nhanVien;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_maNV;
    private javax.swing.JTextField txt_maTK;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
